" Keymaps
inoremap jk <Esc>

" Options
set number
set relativenumber

set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4

set autoindent
set smartindent

set nohlsearch
set incsearch
set ignorecase
set smartcase

set scrolloff=8
